### ISSUE TITLE
No League of legends folder

### ISSUE THREAD

**Issue by Flexxi5** [marvinscham/disenchanter#102]
**Screenshot**

**Description (if necessary)**
Hi, i wanted to ask if this also works with riot client? Somehow i dont have a LOL folder anymore, only Riot Games/Riot Client and in there the Riot Client.exe
**Version**

**Comment by marvinscham** [comment]
It has to be the League Client. Try right clicking the League Client when it's open, go to Properties and look for the path it's saved in.

**Comment by marvinscham** [comment]
Closed due to inactivity (cannot reproduce)
