### ISSUE TITLE
In the main Readme says "Manual exceptions" but I can't find the option.

### ISSUE THREAD

**Issue by JackER4565** [marvinscham/disenchanter#129]
**Screenshot**
![image](https://github.com/marvinscham/disenchanter/assets/94895169/5d795e37-bee5-478b-938c-58d2284bcaef)

**Description (if necessary)**
In the main Readme says "Manual exceptions" but I can't find the option.
there is no option for manual exceptions, i wanna disenchant all my champion shards but one and I can't do it.
**Version**
current

**Comment by marvinscham** [comment]
Hey, to add manual exclusions you need to choose which selection to exclude from first. For your case that would be option 1, after which you are offered to specify exclusions. Sorry about the confusion!
![image](https://github.com/marvinscham/disenchanter/assets/67930021/291572b3-e991-4dd2-9751-ec07e4a74a45)
