### ISSUE TITLE
Could not grab summoner info. Try restarting your League Client.

### ISSUE THREAD

**Issue by corysimmons** [marvinscham/disenchanter#142]
**Screenshot**
![image](https://github.com/marvinscham/disenchanter/assets/224636/bea494f2-419d-464b-8f6c-1362ee57f9f8)

**Description (if necessary)**
I did restart my League Client then tried it again. Same thing.

**Version**
1.5

**Comment by marvinscham** [comment]
@corysimmons Is the account you are currently logged in with relatively new (created Nov '23 and after)?

I'm thinking this might be related to the way I check for a valid response from the client and its interaction with the Riot ID changes.

**Comment by corysimmons** [comment]
Yes I think it was made slightly after that.

**Comment by marvinscham** [comment]
@corysimmons I just released v1.6.0 which fixes this issue.

**Comment by corysimmons** [comment]
It works, thank you!
