### ISSUE TITLE
Mythic Essence to BE does not work

### ISSUE THREAD

**Issue by Aprilxoxo** [marvinscham/disenchanter#157]
**Screenshot**
![image](https://github.com/marvinscham/disenchanter/assets/34486515/f59dda5b-8858-4996-9076-63fb40a56f11)

**Description (if necessary)**
Fails to turn ME into BE

**Version**
1.7.1

**Comment by marvinscham** [comment]
Thanks for the report, you can update to v1.7.2 which fixes this issue.
