### ISSUE TITLE
Glorious Champion Capsule has no name

### ISSUE THREAD

**Issue by marvinscham** [marvinscham/disenchanter#34]
**Description**
Glorious Champion Capsule is displayed as `CHEST_212`

**Version**
v1.5.0

**Comment by xChickens** [comment]
![image](https://user-images.githubusercontent.com/2402510/193498686-533ea8fc-3bad-4687-a535-bde508b5f339.png)
![image](https://user-images.githubusercontent.com/2402510/193498691-6f9dc23e-c52c-42df-9c11-694bac6abe03.png)
Strategizer emote shows up blank

**Comment by marvinscham** [comment]
Capsule name issue has been fixed in v1.6.0.
Problem with the Strategizer icon was a line break in its internal name (en_US locale), v1.7.1 fixes this.
