### ISSUE TITLE
Disenchants champion shards if you have zero mastery

### ISSUE THREAD

**Issue by AllDayTayTaywou** [marvinscham/disenchanter#87]
**Screenshot**

**Description (if necessary)** I ran it using the option to only disenchant shards so i am able to get to level 7, aka "all shards that have no possible use" and it disenchanted all shards for champions i have zero mastery on, and said "below threshold"

**Version** 1.5

**Comment by marvinscham** [comment]
Thanks for the report! This will be fixed in the next version, I'll probably add another option as I can see a use case in both variations.
