### ISSUE TITLE
Script not showing any options

### ISSUE THREAD

**Issue by radeqqq0** [marvinscham/disenchanter#96]
**Screenshot**
![image](https://user-images.githubusercontent.com/66959174/235295920-9614f21e-88a7-40e7-b00f-6b417d650cc5.png)
**Description (if necessary)**
Script is in the league folder but doesnt work
It doesnt show any options
**Version**
1.5

**Comment by marvinscham** [comment]
The issue seems to be related to the League Client running with admin privileges and could be resolved by starting the League Client with regular privileges.
